frame_width: 360
frame_height: 480
mono_calibration_frames: 10
stereo_calibration_frames: 10
view_resize: 1
checkerboard_box_size_scale : 2.5
checkerboard_rows: 5
checkerboard_columns: 8
cooldown: 100
